# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Crinkly Corner
email: thingywhat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Crinkly Corner -- The life of a diapery deviant; the conundrums of being crinkly
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://diape.red" # the base hostname & protocol for your site
twitter_username: CrinklyFriend
github_username: CrinklyFriend

# Build settings
markdown: kramdown
excerpt_separator: <!-- more -->
